#!/bin/tcsh -f
#-----------------------------------------------------------
# Updates the data/tests directory with pre-computed spectra
# This is a developpement program. Should not be used by anyone 
# else than the authors of the PEGASE-HR code.
#-----------------------------------------------------------

cd data/tests/
cp -f ../user_defined/ages.dat .

rm -rf test_tmp/*

# computes the test files, in ./test/
# Please ignore the error messages.
do_test.tcsh nostop

# copies the computed test files into data/tests/ for reference by future tests
cp -f test_tmp/test_1.fits ./
cp -f test_tmp/test_2.fits ./
cp -f test_tmp/test_ELO.fits ./

